package com.test.webservicetest;

import java.util.List;
import javax.jws.WebMethod;
import javax.jws.WebParam;
import javax.jws.WebResult;
import javax.jws.WebService;
import javax.xml.ws.RequestWrapper;
import javax.xml.ws.ResponseWrapper;

/**
 * This class was generated by the JAX-WS RI. JAX-WS RI 2.1.3-hudson-390-
 * Generated source version: 2.0
 * 
 */
@WebService(name = "HgGoodsInWeighWebService", targetNamespace = "http://service.ws.hg.wuliu.tietie.com/")
public interface HgGoodsInWeighWebService {

	/**
	 * 
	 * @param buyMetricVos
	 * @param startTime
	 * @param webserviceHeader
	 * @param endTime
	 * @return returns com.test.webservicetest.ResponseResult
	 */
	@WebMethod
	@WebResult(targetNamespace = "")
	@RequestWrapper(localName = "addBuyMetricInfo", targetNamespace = "http://service.ws.hg.wuliu.tietie.com/", className = "com.test.webservicetest.AddBuyMetricInfo")
	@ResponseWrapper(localName = "addBuyMetricInfoResponse", targetNamespace = "http://service.ws.hg.wuliu.tietie.com/", className = "com.test.webservicetest.AddBuyMetricInfoResponse")
	public ResponseResult addBuyMetricInfo(
			@WebParam(name = "webserviceHeader", targetNamespace = "") WebserviceHeader webserviceHeader,
			@WebParam(name = "startTime", targetNamespace = "") String startTime,
			@WebParam(name = "endTime", targetNamespace = "") String endTime,
			@WebParam(name = "buyMetricVos", targetNamespace = "") List<HgGoodsInWeighInfoVo> buyMetricVos);

}
